# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: manishguptakibbcom/go-k8s
  tag: 0.0.1
  pullPolicy: IfNotPresent

service:
  name: go-app
  type: NodePort
  externalPort: 8080
  internalPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi


